// All UI strings + the artist statement, in zh-TW and en.
window.COPY = {
  zh: {
    lang_label: "繁中",
    artist: "吳享龍",
    artist_en: "Dragom",
    role: "繪畫工作者",
    nav: {
      home: "首頁",
      works: "作品",
      series: "系列",
      statement: "創作自述",
      journal: "手記",
      about: "關於",
      contact: "聯絡",
    },
    landing: {
      eyebrow: "個人作品集 ｜ 二〇二一 – 二〇二六",
      hero_title: "在空無一人的世界，",
      hero_title_2: "來一場與自我的對話。",
      hero_lede:
        "手繪作品，記錄潛意識湧動之處——當社會的鷹架抵不住內裡的洪流，個體將以何種姿態落地。",
      enter: "進入畫廊",
      featured_label: "本期主作 ／ Featured",
      index_label: "作品索引 ／ Index",
      manifesto_eyebrow: "創作自述 ／ Manifesto",
      manifesto_cta: "閱讀全文",
      scroll_hint: "向下，慢慢看",
    },
    statement_title: "創作自述",
    statement_subtitle: "Statement",
    statement_body: [
      "我畫出一個空無一人的世界。\n在這片空曠而寧靜的場域裡，展開與自我的對話。\n當喧囂褪去，拋開人類的框架，你會看見什麼？\n這樣的提問，始終貫穿於我的創作之中。",
    ],
    gallery: {
      title: "作品",
      subtitle: "Works",
      total: "個人作品集",
      pieces_label: "件作品",
      layout_label: "陳列方式",
      layouts: {
        spotlight: "聚光燈",
        grid: "網格",
        masonry: "瀑布流",
        editorial: "編輯",
      },
      filter_all: "全部",
      filter_series: "系列",
      caption_label: "作品說明",
      medium_label: "媒材",
      size_label: "尺寸",
      year_label: "年份",
      series_label: "系列",
      prev: "上一件",
      next: "下一件",
      view: "查看",
      back_to_index: "返回索引",
    },
    series_page: {
      title: "系列",
      subtitle: "Series",
      lede: "兩組作品，從寓言裡的龍，走到眼前的寫生。",
      pieces: "件作品",
    },
    journal: {
      title: "手記",
      subtitle: "Journal",
      lede: "工作室裡的碎片、媒材的整理、過程中的速寫、偶爾的活動照片。把這裡當作一條時間的邊線，作品成形之前與之後的事都安放在此。",
      foot_hint: "拖一張圖進任何一格 ／ 它會記住",
    },
    about: {
      title: "關於",
      subtitle: "About",
      bio_eyebrow: "簡介",
      bio: [
        "吳享龍（Dragom），1994年生於臺灣。他以繪畫作為思考與對話的媒介，透過安靜而內斂的視覺語彙，凝視社會議題如何映照於個人的內在世界。\n其作品以溫和、沉靜的畫面語言展開提問，在看似柔軟的敘事之中，持續追索社會框架與內在自我之間的張力。當既有秩序與外在框架逐漸鬆動甚至被剝除，人如何理解自身，又將走向何方，成為其創作長期關注的核心。",
      ],
      cv_eyebrow: "經歷",
      cv: [
        ["2024", "「異次元」台北新藝術博覽會，台北世貿一館"],
        ["2023", "「希望的所在」插畫創作聯展，典美藝文空間"],
        ["2022", "《紙上躍躍然．典美插畫大賞_轉動希望的曙光》 決選入圍"],
      ],
    },
    contact: {
      title: "聯絡",
      subtitle: "Contact",
      lede: "歡迎邀稿、合作、徵件、收藏與課程提案。一般於三個工作日內回覆。",
      email_label: "電子郵件",
      ig_label: "Instagram",
      copy: "複製",
      copied: "已複製",
      open: "開啟",
      footer_invite: "收藏作品、委託訂製、合作，歡迎洽詢。",
      footer_note: "本網站作品著作權所有，未經同意請勿轉載。",
    },
    plaque: {
      catalog: "目錄編號",
      medium: "媒材",
      dimensions: "尺寸",
      year: "年份",
      series: "系列",
    },
  },
  en: {
    lang_label: "EN",
    artist: "Dragom",
    artist_en: "Wu Hsiang-Lung",
    role: "Painter",
    nav: {
      home: "Index",
      works: "Works",
      series: "Series",
      statement: "Statement",
      journal: "Journal",
      about: "About",
      contact: "Contact",
    },
    landing: {
      eyebrow: "Selected works ｜ 2021 – 2026",
      hero_title: "In a world with no one in it,",
      hero_title_2: "a conversation with the self.",
      hero_lede:
        "Hand-drawn pieces from where the subconscious moves — when the social scaffolding fails to hold the current inside, how does the self land.",
      enter: "Enter the gallery",
      featured_label: "Featured work",
      index_label: "Index of works",
      manifesto_eyebrow: "Statement ／ Manifesto",
      manifesto_cta: "Read in full",
      scroll_hint: "Down. Take your time.",
    },
    statement_title: "Statement",
    statement_subtitle: "創作自述",
    statement_body: [
      "I paint a world with no one in it.\nWithin this empty, quiet expanse, a conversation with the self begins.\nWhen the noise falls away and the human frame is set aside, what is it that you would see?\nThat question has run through my work from the very start.",
    ],
    gallery: {
      title: "Works",
      subtitle: "作品",
      total: "Selected works",
      pieces_label: "works",
      layout_label: "Layout",
      layouts: {
        spotlight: "Spotlight",
        grid: "Grid",
        masonry: "Masonry",
        editorial: "Editorial",
      },
      filter_all: "All",
      filter_series: "Series",
      caption_label: "Caption",
      medium_label: "Medium",
      size_label: "Size",
      year_label: "Year",
      series_label: "Series",
      prev: "Previous",
      next: "Next",
      view: "View",
      back_to_index: "Back to index",
    },
    series_page: {
      title: "Series",
      subtitle: "系列",
      lede: "Two bodies of work — from the dragons of fable to drawing what stands before you.",
      pieces: "works",
    },
    journal: {
      title: "Journal",
      subtitle: "手記",
      lede: "Fragments from the studio, organising materials, in-process sketches, the occasional event photograph. Treat it as a line of time — anything that lives before and after a finished work goes here.",
      foot_hint: "drop an image into any slot ／ it will remember",
    },
    about: {
      title: "About",
      subtitle: "關於",
      bio_eyebrow: "Bio",
      bio: [
        "Dragom (Wu Hsiang-Lung), born in Taiwan in 1994, works through painting — using a quiet vocabulary to question the relationship between his subjects and everyday life.\nThe surfaces look soft, yet within them he keeps asking about frames and where the individual stands: when the outer frame is stripped away, where do we — as human beings — go from here?",
      ],
      cv_eyebrow: "Experience",
      cv: [
        ["2024", "“Another Dimension” Taipei New Art Fair, Taipei World Trade Center Hall 1"],
        ["2023", "“Where Hope Lies” illustration group exhibition, Dianmei Art Space"],
        ["2022", "Finalist — Dianmei Illustration Award, “Turning the Light of Hope”"],
      ],
    },
    contact: {
      title: "Contact",
      subtitle: "聯絡",
      lede: "Open to commissions, collaborations, open calls, acquisitions and teaching. Usually replies within three working days.",
      email_label: "Email",
      ig_label: "Instagram",
      copy: "Copy",
      copied: "Copied",
      open: "Open",
      footer_invite: "For acquisitions, commissions and collaborations — inquiries are welcome.",
      footer_note: "All works © the artist. Please don't repost without permission.",
    },
    plaque: {
      catalog: "Catalog",
      medium: "Medium",
      dimensions: "Dimensions",
      year: "Year",
      series: "Series",
    },
  },
};

window.CONTACT = {
  email: "dragom3608@hotmail.com",
  ig: "chishathatplanett",
  ig_url: "https://instagram.com/chishathatplanett",
};
