// Artwork data — bilingual metadata for all 25 paintings.
// Titles, years and series are from the artist's filenames + uploads.
// Years are read from artist's signatures where visible (format YYMM).
// Items without a `series` belong to no formal series and appear only in
// the "all" view of the gallery filter.

window.SERIES = [
  {
    id: "dragon-by-dragom",
    no: "I",
    zh: {
      name: "Dragon By Dragom",
      note: "夢境裡的角色們。油性粉彩、紙，多數為 54.5 × 39.3 公分。",
    },
    en: {
      name: "Dragon By Dragom",
      note: "Characters from the dream. Oil pastel on paper, mostly 54.5 × 39.3 cm.",
    },
  },
  {
    id: "mood-tiles",
    no: "II",
    zh: {
      name: "心情磁磚",
      note: "用方寸格子放著當天的心情。一格一塊，留白也算數。",
    },
    en: {
      name: "Mood Tiles",
      note: "Each square holds a single day's mood. The empty squares count too.",
    },
  },
  {
    id: "plein-air",
    no: "III",
    zh: {
      name: "寫生",
      note: "離開工作室，把光、街角、季節留在紙上。",
    },
    en: {
      name: "Plein Air",
      note: "Leaving the studio — keeping light, street corners, and the seasons on paper.",
    },
  },
];

// Aspect can be either a category string ("wide" / "tall" / "square" /
// "panorama") or a numeric width/height ratio. Numeric wins. See artwork.jsx.

window.ARTWORKS = [
  // ─── No-series ──────────────────────────────────────────────────────────
  {
    id: "01",
    bordered: true,
    src: "assets/artwork-01.jpeg",
    aspect: 2400 / 1263,
    year: 2026,
    medium: { zh: "粉彩、有色紙", en: "Soft pastel on toned paper" },
    size: { zh: "54 × 28 公分", en: "54 × 28 cm" },
    zh: {
      title: "歸途",
      sub: "從公寓窗台的高度，城市退場",
      caption:
        "光從不存在的方向射來，落在玻璃塔尖。當理性的建築被微亮的夜色重新組合，居住者在無人察覺時，悄悄離開了自己。",
    },
    en: {
      title: "The Way Home",
      sub: "From the height of an apartment ledge, the city exits",
      caption:
        "Light arrives from a direction that does not exist and lands on the glass spire. When rational architecture is reassembled by a faintly luminous night, the inhabitant slips, unnoticed, out of himself.",
    },
  },
  {
    id: "02",
    src: "assets/artwork-02.jpg",
    aspect: 2400 / 1013,
    year: 2025,
    medium: { zh: "油彩、畫布", en: "Oil on canvas" },
    zh: { title: "下午茶時間", sub: "綠草上的紅格、漂浮的物件" },
    en: { title: "Tea Time", sub: "Red checks on green grass, things half-rising" },
  },
  {
    id: "03",
    bordered: true,
    src: "assets/artwork-03.jpg",
    aspect: 2347 / 1705,
    year: 2026,
    medium: { zh: "粉彩、有色紙", en: "Soft pastel on toned paper" },
    zh: { title: "馬吃一口", sub: "鑲了金邊的天空" },
    en: { title: "One Bite", sub: "A sky in a gilded frame" },
  },
  {
    id: "04",
    bordered: true,
    src: "assets/artwork-04.jpg",
    aspect: 2360 / 2371,
    year: 2025,
    series: "mood-tiles",
    medium: { zh: "油性粉彩、有色紙", en: "Oil pastel on toned paper" },
    zh: { title: "藍磁磚", sub: "色彩的小研究" },
    en: { title: "Blue Tiles", sub: "A small study in colour" },
  },
  {
    id: "05",
    src: "assets/artwork-05.jpg",
    aspect: 1,
    year: 2024,
    series: "mood-tiles",
    medium: { zh: "油性粉彩、有色紙", en: "Oil pastel on toned paper" },
    zh: { title: "粉磁磚", sub: "藏著愛心的色彩" },
    en: { title: "Pink Tiles", sub: "Hearts tucked into the colour" },
  },
  {
    id: "06",
    src: "assets/artwork-06.jpg",
    aspect: 2004 / 2400,
    year: 2026,
    medium: { zh: "粉彩、紙", en: "Soft pastel on paper" },
    zh: { title: "巷弄", sub: "陽光從另一條街上倒進來" },
    en: { title: "Alley", sub: "Light pours in from the next street over" },
  },
  {
    id: "07",
    bordered: true,
    src: "assets/artwork-07.jpg",
    aspect: 1730 / 2400,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    zh: { title: "向左", sub: "森林邊的指標" },
    en: { title: "Left", sub: "A sign at the edge of the woods" },
  },
  {
    id: "08",
    src: "assets/artwork-08.jpg",
    aspect: 2400 / 1732,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    zh: { title: "回憶", sub: "牆上的金魚仍在動" },
    en: { title: "Recollection", sub: "The goldfish on the wall are still moving" },
  },
  {
    id: "09",
    bordered: true,
    src: "assets/artwork-09.jpg",
    aspect: 2381 / 1680,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    zh: { title: "秋日之約", sub: "落葉先到了" },
    en: { title: "An Autumn Appointment", sub: "The leaves arrived first" },
  },
  {
    id: "10",
    src: "assets/artwork-10.jpg",
    aspect: 1702 / 2400,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    zh: { title: "秋日之舞", sub: "她揚起整座森林" },
    en: { title: "Autumn Dance", sub: "She tosses the whole forest up" },
  },
  {
    id: "11",
    src: "assets/artwork-11.jpg",
    aspect: 2400 / 1669,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    zh: { title: "浪漫襲來", sub: "浪花裡藏著玫瑰" },
    en: { title: "When Romance Arrives", sub: "Roses hidden in the foam" },
  },

  // ─── Dragon By Dragom ───────────────────────────────────────────────────
  {
    id: "12",
    src: "assets/artwork-12.jpg",
    aspect: 2400 / 1597,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "書本龍", sub: "夜城裡的書本城堡" },
    en: { title: "The Book Dragon", sub: "A castle of books in the night city" },
  },
  {
    id: "13",
    src: "assets/artwork-13.jpg",
    aspect: 2400 / 1722,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "鬱金香", sub: "懷裡的春天" },
    en: { title: "Tulips", sub: "Spring held in the arms" },
  },
  {
    id: "14",
    src: "assets/artwork-14.jpg",
    aspect: 2400 / 1714,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "列車夢境", sub: "車窗外的綠色山脊" },
    en: { title: "Dream Train", sub: "A green ridge passes the window" },
  },
  {
    id: "15",
    src: "assets/artwork-15.jpg",
    aspect: 2400 / 1706,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "星星龍", sub: "雲海裡的小小光" },
    en: { title: "Star Dragon", sub: "A small light afloat the cloud sea" },
  },
  {
    id: "16",
    src: "assets/artwork-16.jpg",
    aspect: 2400 / 1690,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "飛天貓", sub: "向上的姿勢、向上的翅膀" },
    en: { title: "Flying Cat", sub: "Reaching upward, with wings" },
  },
  {
    id: "17",
    src: "assets/artwork-17.jpg",
    aspect: 2400 / 1736,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "永恆的見證", sub: "海邊的兩張椅子、空中的彗星" },
    en: { title: "Eternal Witness", sub: "Two chairs at the shore, a comet above" },
  },
  {
    id: "18",
    src: "assets/artwork-18.jpg",
    aspect: 2400 / 1704,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "龍大廚", sub: "爐前的桃花與烈火" },
    en: { title: "Dragon Chef", sub: "Peach blossoms and roaring flame" },
  },
  {
    id: "19",
    src: "assets/artwork-19.jpg",
    aspect: 2400 / 1721,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "追逐", sub: "海上單車、雲端的龍尾" },
    en: { title: "Chase", sub: "A bicycle on the sea, a dragon's tail in cloud" },
  },
  {
    id: "20",
    src: "assets/artwork-20.jpg",
    aspect: 2400 / 1714,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "煙囪", sub: "紅頂、紅龍、餘燼" },
    en: { title: "Chimney", sub: "Red roof, red dragon, embers" },
  },
  {
    id: "21",
    bordered: true,
    src: "assets/artwork-21.jpg",
    aspect: 2352 / 1673,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "遺世之龍", sub: "檯燈下守著一座小城堡" },
    en: { title: "Solitary Dragon", sub: "Guarding a small castle beneath a lamp" },
  },
  {
    id: "22",
    src: "assets/artwork-22.jpg",
    aspect: 2400 / 1694,
    year: 2024,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.5 × 39.3 公分", en: "54.5 × 39.3 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "警告", sub: "牆上的封條、樹下的安靜" },
    en: { title: "Warning", sub: "Seals on the wall, silence under the tree" },
  },

  // ─── No-series ──────────────────────────────────────────────────────────
  {
    id: "23",
    bordered: true,
    src: "assets/artwork-23.jpg",
    aspect: 2393 / 1746,
    year: 2024,
    medium: { zh: "油彩、紙", en: "Oil on paper" },
    zh: { title: "燈火", sub: "藍色洪水中還亮著" },
    en: { title: "Lantern", sub: "Still burning in the blue flood" },
  },
  {
    id: "24",
    bordered: true,
    src: "assets/artwork-24.jpg",
    aspect: 2375 / 2002,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    zh: { title: "綠磚牆上的擱物", sub: "錯落的層架" },
    en: { title: "Things on a Green Wall", sub: "Shelves out of alignment" },
  },
  {
    id: "25",
    bordered: true,
    src: "assets/artwork-25.jpg",
    aspect: 2400 / 1733,
    year: 2022,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    zh: { title: "Teenage Love", sub: "桌椅的傾斜、地上的小花車" },
    en: { title: "Teenage Love", sub: "Tilted desks, a small flower cart on the floor" },
  },
];
