// Artwork data — bilingual metadata for all 25 paintings.
// Titles, years and series are from the artist's filenames + uploads.
// Years are read from artist's signatures where visible (format YYMM).
// Items without a `series` belong to no formal series and appear only in
// the "all" view of the gallery filter.

window.SERIES = [
  {
    id: "dragon-by-dragom",
    no: "I",
    zh: {
      name: "Dragon By Dragom",
      note: "夢境裡的角色們。油性粉彩、紙，多數為 54.5 × 39.3 公分。",
    },
    en: {
      name: "Dragon By Dragom",
      note: "Characters from the dream. Oil pastel on paper, mostly 54.5 × 39.3 cm.",
    },
  },
  {
    id: "mood-tiles",
    no: "II",
    zh: {
      name: "心情磁磚",
      note: "用方寸格子放著當天的心情。一格一塊，留白也算數。",
    },
    en: {
      name: "Mood Tiles",
      note: "Each square holds a single day's mood. The empty squares count too.",
    },
  },
  {
    id: "plein-air",
    no: "III",
    zh: {
      name: "寫生",
      note: "離開工作室，把光、街角、季節留在紙上。",
    },
    en: {
      name: "Plein Air",
      note: "Leaving the studio — keeping light, street corners, and the seasons on paper.",
    },
  },
];

// Aspect can be either a category string ("wide" / "tall" / "square" /
// "panorama") or a numeric width/height ratio. Numeric wins. See artwork.jsx.

window.ARTWORKS = [
  // ─── No-series ──────────────────────────────────────────────────────────
  {
    id: "01",
    bordered: true,
    src: "assets/artwork-01.jpg",
    aspect: 2400 / 1255,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "57.0 × 29.8 公分", en: "57.0 × 29.8 cm" },
    zh: {
      title: "歸途",
      sub: "",
      caption: "",
    },
    en: {
      title: "The Way Home",
      sub: "",
      caption: "",
    },
  },
  {
    id: "03",
    bordered: true,
    src: "assets/artwork-03.jpg",
    aspect: 2347 / 1705,
    year: 2026,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "馬吃一口", sub: "" },
    en: { title: "One Bite", sub: "" },
  },
  {
    id: "06",
    src: "assets/artwork-06.jpg",
    aspect: 1994 / 2400,
    year: 2026,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "即將到來", sub: "SIZE N" },
    en: { title: "Alley", sub: "" },
  },
  {
    id: "02",
    src: "assets/artwork-02.jpg",
    aspect: 2400 / 1013,
    year: 2025,
    medium: { zh: "油性粉彩、木板", en: "Oil pastel on wood" },
    size: { zh: "90.0 × 38.0 公分", en: "90.0 × 38.0 cm" },
    zh: { title: "下午茶時間", sub: "SIZE N" },
    en: { title: "Tea Time", sub: "" },
  },
  {
    id: "11",
    src: "assets/artwork-11.jpg",
    aspect: 2400 / 1669,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "浪漫襲來", sub: "" },
    en: { title: "When Romance Arrives", sub: "" },
  },
  {
    id: "24",
    bordered: true,
    src: "assets/artwork-24.jpg",
    aspect: 2375 / 2002,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "43.9 × 36.5 公分", en: "43.9 × 36.5 cm" },
    zh: { title: "奮不顧身", sub: "" },
    en: { title: "Things on a Green Wall", sub: "" },
  },
  {
    id: "07",
    bordered: true,
    src: "assets/artwork-07.jpg",
    aspect: 1730 / 2400,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "尋找", sub: "size n" },
    en: { title: "Left", sub: "" },
  },
  {
    id: "08",
    src: "assets/artwork-08.jpg",
    aspect: 2400 / 1732,
    year: 2022,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "回憶", sub: "" },
    en: { title: "Recollection", sub: "" },
  },
  {
    id: "09",
    bordered: true,
    src: "assets/artwork-09.jpg",
    aspect: 2400 / 1647,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "39.2 × 27.3 公分", en: "39.2 × 27.3 cm" },
    zh: { title: "秋日之約", sub: "" },
    en: { title: "An Autumn Appointment", sub: "" },
  },
  {
    id: "10",
    src: "assets/artwork-10.jpg",
    aspect: 1702 / 2400,
    year: 2022,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "秋天之舞", sub: "" },
    en: { title: "Autumn Dance", sub: "" },
  },
  {
    id: "23",
    bordered: true,
    src: "assets/artwork-23.jpg",
    aspect: 2393 / 1746,
    year: 2024,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "燈火", sub: "Size n" },
    en: { title: "Lantern", sub: "" },
  },
  {
    id: "25",
    bordered: true,
    src: "assets/artwork-25.jpg",
    aspect: 2400 / 1733,
    year: 2023,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "Teenage Love", sub: "" },
    en: { title: "Teenage Love", sub: "" },
  },
  {
    id: "26",
    src: "assets/artwork-26.jpg",
    aspect: 2400 / 1697,
    year: 2023,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "偷窺兔", sub: "", caption: "" },
    en: { title: "Peeping Rabbit", sub: "", caption: "" },
  },
  {
    id: "27",
    src: "assets/artwork-27.jpg",
    aspect: 1675 / 2400,
    year: 2022,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "對街傳情", sub: "", caption: "" },
    en: { title: "Affection Across the Street", sub: "", caption: "" },
  },
  {
    id: "28",
    src: "assets/artwork-28.jpg",
    aspect: 1745 / 2400,
    year: 2023,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "變出美味的魔法午後時光", sub: "", caption: "" },
    en: { title: "A Magical Afternoon of Cooking", sub: "", caption: "" },
  },
  {
    id: "29",
    src: "assets/artwork-29.jpg",
    aspect: 2400 / 1694,
    year: 2020,
    medium: { zh: "水彩、色鉛筆、紙", en: "Watercolor on paper" },
    size: { zh: "37.8 × 28.0 公分", en: "37.8 × 28.0 cm" },
    zh: { title: "靜謐之森", sub: "", caption: "" },
    en: { title: "The Quiet Forest", sub: "", caption: "" },
  },
  {
    id: "04",
    bordered: true,
    src: "assets/artwork-04.jpg",
    aspect: 2400 / 2383,
    year: 2025,
    series: "mood-tiles",
    medium: { zh: "油性粉彩、有色紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "藍磁磚", sub: "" },
    en: { title: "Blue Tiles", sub: "" },
  },
  {
    id: "05",
    src: "assets/artwork-05.jpg",
    aspect: 1,
    year: 2024,
    series: "mood-tiles",
    medium: { zh: "油性粉彩、有色紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "粉磁磚", sub: "" },
    en: { title: "Pink Tiles", sub: "" },
  },
  {
    id: "12",
    src: "assets/artwork-12.jpg",
    aspect: 2400 / 1597,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "書本龍", sub: "" },
    en: { title: "The Book Dragon", sub: "" },
  },
  {
    id: "13",
    src: "assets/artwork-13.jpg",
    aspect: 2400 / 1722,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "鬱金香", sub: "" },
    en: { title: "Tulips", sub: "" },
  },
  {
    id: "14",
    src: "assets/artwork-14.jpg",
    aspect: 2400 / 1714,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "列車夢境", sub: "" },
    en: { title: "Dream Train", sub: "" },
  },
  {
    id: "15",
    src: "assets/artwork-15.jpg",
    aspect: 2400 / 1706,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "星星龍", sub: "" },
    en: { title: "Star Dragon", sub: "" },
  },
  {
    id: "16",
    src: "assets/artwork-16.jpg",
    aspect: 2400 / 1690,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "飛天貓", sub: "" },
    en: { title: "Flying Cat", sub: "" },
  },
  {
    id: "17",
    src: "assets/artwork-17.jpg",
    aspect: 2400 / 1736,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "永恆的見證", sub: "" },
    en: { title: "Eternal Witness", sub: "" },
  },
  {
    id: "18",
    src: "assets/artwork-18.jpg",
    aspect: 2400 / 1704,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "龍大廚", sub: "" },
    en: { title: "Dragon Chef", sub: "" },
  },
  {
    id: "19",
    src: "assets/artwork-19.jpg",
    aspect: 2400 / 1721,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "追逐", sub: "" },
    en: { title: "Chase", sub: "" },
  },
  {
    id: "20",
    src: "assets/artwork-20.jpg",
    aspect: 2400 / 1714,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "甦醒之秋", sub: "" },
    en: { title: "Chimney", sub: "" },
  },
  {
    id: "21",
    bordered: true,
    src: "assets/artwork-21.jpg",
    aspect: 2352 / 1673,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "遺世之龍", sub: "" },
    en: { title: "Solitary Dragon", sub: "" },
  },
  {
    id: "22",
    src: "assets/artwork-22.jpg",
    aspect: 2400 / 1694,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    price: { zh: "NT$ 15,000", en: "NT$ 15,000" },
    zh: { title: "警告", sub: "" },
    en: { title: "Warning", sub: "" },
  },
];
