// Artwork data — bilingual metadata for all 29 paintings.
// Titles, years and series are from the artist's filenames + uploads.
// Years are read from artist's signatures where visible (format YYMM).
// Items without a `series` belong to no formal series and appear only in
// the "all" view of the gallery filter.

window.SERIES = [
  {
    id: "dragon-by-dragom",
    no: "I",
    zh: {
      name: "Dragon By Dragom",
      note: "希望它們永遠存在世界上的某的角落。",
    },
    en: {
      name: "Dragon By Dragom",
      note: "I hope they live on forever, in some corner of the world.",
    },
  },
  {
    id: "plein-air",
    no: "II",
    zh: {
      name: "寫生",
      note: "",
    },
    en: {
      name: "Plein Air",
      note: "",
    },
  },
  {
    id: "mood-tiles",
    no: "III",
    zh: {
      name: "心情磁磚",
      note: "",
    },
    en: {
      name: "Mood Tiles",
      note: "",
    },
  },
];

// Aspect can be either a category string ("wide" / "tall" / "square" /
// "panorama") or a numeric width/height ratio. Numeric wins. See artwork.jsx.

window.ARTWORKS = [
  // ─── No-series ──────────────────────────────────────────────────────────
  {
    id: "01",
    bordered: true,
    src: "assets/artwork-01.jpg",
    aspect: 2400 / 1255,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "57.0 × 29.8 公分", en: "57.0 × 29.8 cm" },
    zh: {
      title: "歸途",
      sub: "",
      caption: "",
    },
    en: {
      title: "The Way Home",
      sub: "",
      caption: "",
    },
  },
  {
    id: "03",
    bordered: true,
    src: "assets/artwork-03.jpg",
    aspect: 2347 / 1705,
    year: 2026,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "馬吃一口", sub: "" },
    en: { title: "One Bite", sub: "" },
  },
  {
    id: "06",
    src: "assets/artwork-06.jpg",
    aspect: 1994 / 2400,
    year: 2026,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "即將到來", sub: "SIZE N" },
    en: { title: "Approaching", sub: "SIZE N" },
  },
  {
    id: "02",
    src: "assets/artwork-02.jpg",
    aspect: 2400 / 1013,
    year: 2025,
    medium: { zh: "油性粉彩、木板", en: "Oil pastel on wood" },
    size: { zh: "90.0 × 38.0 公分", en: "90.0 × 38.0 cm" },
    zh: { title: "下午茶時間", sub: "SOLD\nSIZE N" },
    en: { title: "Tea Time", sub: "SOLD\nSIZE N" },
  },
  {
    id: "11",
    src: "assets/artwork-11.jpg",
    aspect: 2400 / 1669,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "浪漫襲來", sub: "" },
    en: { title: "When Romance Arrives", sub: "" },
  },
  {
    id: "24",
    bordered: true,
    src: "assets/artwork-24.jpg",
    aspect: 2400 / 1965,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "43.9 × 36.5 公分", en: "43.9 × 36.5 cm" },
    zh: { title: "奮不顧身", sub: "" },
    en: { title: "Reckless Abandon", sub: "" },
  },
  {
    id: "07",
    bordered: true,
    src: "assets/artwork-07.jpg",
    aspect: 1490 / 2108,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "尋找", sub: "size n" },
    en: { title: "Searching", sub: "SIZE N" },
  },
  {
    id: "08",
    src: "assets/artwork-08.jpg",
    aspect: 2400 / 1732,
    year: 2022,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "回憶", sub: "" },
    en: { title: "Recollection", sub: "" },
  },
  {
    id: "09",
    bordered: true,
    src: "assets/artwork-09.jpg",
    aspect: 2400 / 1647,
    year: 2025,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "39.2 × 27.3 公分", en: "39.2 × 27.3 cm" },
    zh: { title: "秋日之約", sub: "" },
    en: { title: "An Autumn Appointment", sub: "" },
  },
  {
    id: "10",
    src: "assets/artwork-10.jpg",
    aspect: 1702 / 2400,
    year: 2022,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "秋天之舞", sub: "" },
    en: { title: "Autumn Dance", sub: "" },
  },
  {
    id: "23",
    bordered: true,
    src: "assets/artwork-23.jpg",
    aspect: 2400 / 1724,
    year: 2024,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "希望", sub: "Size n" },
    en: { title: "Hope", sub: "SIZE N" },
  },
  {
    id: "25",
    bordered: true,
    src: "assets/artwork-25.jpg",
    aspect: 2400 / 1708,
    year: 2023,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "Teenage Love", sub: "" },
    en: { title: "Teenage Love", sub: "" },
  },
  {
    id: "26",
    src: "assets/artwork-26.jpg",
    aspect: 2400 / 1706,
    year: 2023,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "偷窺兔", sub: "SOLD", caption: "" },
    en: { title: "Peeping Rabbit", sub: "SOLD", caption: "" },
  },
  {
    id: "27",
    src: "assets/artwork-27.jpg",
    aspect: 1675 / 2400,
    year: 2022,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "對街傳情", sub: "SOLD", caption: "" },
    en: { title: "Affection Across the Street", sub: "SOLD", caption: "" },
  },
  {
    id: "28",
    src: "assets/artwork-28.jpg",
    aspect: 1746 / 2400,
    year: 2023,
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "40.5 × 29.7 公分", en: "40.5 × 29.7 cm" },
    zh: { title: "變出美味的魔法午後時光", sub: "SOLD", caption: "" },
    en: { title: "A Magical Afternoon of Cooking", sub: "SOLD", caption: "" },
  },
  {
    id: "29",
    src: "assets/artwork-29.jpg",
    aspect: 2400 / 1694,
    year: 2020,
    medium: { zh: "水彩、色鉛筆、紙", en: "Watercolor and colored pencil on paper" },
    size: { zh: "37.8 × 28.0 公分", en: "37.8 × 28.0 cm" },
    zh: { title: "靜謐之森", sub: "SOLD", caption: "" },
    en: { title: "The Quiet Forest", sub: "SOLD", caption: "" },
  },
  {
    id: "04",
    bordered: true,
    src: "assets/artwork-04.jpg",
    aspect: 2400 / 2384,
    year: 2025,
    series: "mood-tiles",
    medium: { zh: "油性粉彩、有色紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "笑臉", sub: "" },
    en: { title: "Smiling Face", sub: "" },
  },
  {
    id: "05",
    src: "assets/artwork-05.jpg",
    aspect: 1,
    year: 2024,
    series: "mood-tiles",
    medium: { zh: "油性粉彩、有色紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "心動", sub: "" },
    en: { title: "Heart Flutter", sub: "" },
  },
  {
    id: "12",
    src: "assets/artwork-12.jpg",
    aspect: 2400 / 1597,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" }, 
    zh: { title: "書本龍", sub: "" },
    en: { title: "The Book Dragon", sub: "" },
  },
  {
    id: "13",
    src: "assets/artwork-13.jpg",
    aspect: 2400 / 1722,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "禮物", sub: "" },
    en: { title: "The Gift", sub: "" },
  },
  {
    id: "14",
    src: "assets/artwork-14.jpg",
    aspect: 2400 / 1714,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "列車夢境", sub: "SOLD" },
    en: { title: "Dream Train", sub: "SOLD" },
  },
  {
    id: "15",
    src: "assets/artwork-15.jpg",
    aspect: 2400 / 1706,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "星星龍", sub: "SOLD" },
    en: { title: "Star Dragon", sub: "SOLD" },
  },
  {
    id: "16",
    src: "assets/artwork-16.jpg",
    aspect: 2400 / 1690,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "飛天貓", sub: "SOLD" },
    en: { title: "Flying Cat", sub: "SOLD" },
  },
  {
    id: "17",
    src: "assets/artwork-17.jpg",
    aspect: 2400 / 1736,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "永恆的見證", sub: "" },
    en: { title: "Eternal Witness", sub: "" },
  },
  {
    id: "18",
    src: "assets/artwork-18.jpg",
    aspect: 2400 / 1704,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "龍大廚", sub: "" },
    en: { title: "Dragon Chef", sub: "" },
  },
  {
    id: "19",
    src: "assets/artwork-19.jpg",
    aspect: 2400 / 1721,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "追逐", sub: "" },
    en: { title: "Chase", sub: "" },
  },
  {
    id: "20",
    src: "assets/artwork-20.jpg",
    aspect: 2400 / 1714,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "甦醒之秋", sub: "" },
    en: { title: "Autumn Awakening", sub: "" },
  },
  {
    id: "21",
    bordered: true,
    src: "assets/artwork-21.jpg",
    aspect: 2352 / 1673,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "遺世之龍", sub: "SOLD" },
    en: { title: "Solitary Dragon", sub: "SOLD" },
  },
  {
    id: "22",
    src: "assets/artwork-22.jpg",
    aspect: 2400 / 1694,
    year: 2023,
    series: "dragon-by-dragom",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "54.1 × 39.2 公分", en: "54.1 × 39.2 cm" },
    zh: { title: "警告", sub: "" },
    en: { title: "Warning", sub: "" },
  },

  // ─── Plein Air ／ 寫生 ───────────────────────────────────────────────────
  // Field sketches in oil pastel — left uncropped on purpose, keeping the raw,
  // in-the-field feel (the lap, the pastel tin, the ground all stay in frame).
  {
    id: "30",
    src: "assets/artwork-30.jpg",
    aspect: 1.408,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "兼六園", sub: "" },
    en: { title: "Kenrokuen Garden", sub: "" },
  },
  {
    id: "46",
    src: "assets/artwork-46.jpg",
    aspect: 1.333,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "雨晴海岸／あまはらしかいがん", sub: "" },
    en: { title: "Amaharashi Coast", sub: "" },
  },
  {
    id: "47",
    src: "assets/artwork-47.jpg",
    aspect: 0.75,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "静岡駅／しずおかえき", sub: "" },
    en: { title: "Shizuoka Station", sub: "" },
  },
  {
    id: "45",
    src: "assets/artwork-45.jpg",
    aspect: 1.333,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "基隆停車場", sub: "" },
    en: { title: "Keelung Car Park", sub: "" },
  },
  {
    id: "42",
    src: "assets/artwork-42.jpg",
    aspect: 1.314,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "雲林鄉間", sub: "" },
    en: { title: "Yunlin Countryside", sub: "" },
  },
  {
    id: "43",
    src: "assets/artwork-43.jpg",
    aspect: 1.333,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "嘉義北香湖公園", sub: "" },
    en: { title: "Beixiang Lake Park, Chiayi", sub: "" },
  },
  {
    id: "44",
    src: "assets/artwork-44.jpg",
    aspect: 1.333,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "阿嬤家", sub: "" },
    en: { title: "Grandmother's House", sub: "" },
  },
  {
    id: "41",
    src: "assets/artwork-41.jpg",
    aspect: 1.333,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "午後的伸展", sub: "在下過雨的午後，伸展一下僵硬的樹枝，搖動一下樹梢，發出沙沙沙的聲音。\n富邦美術館。" },
    en: { title: "Afternoon Stretch", sub: "On an afternoon after the rain, the stiff branches stretch a little, the treetops sway and rustle.\nFubon Art Museum." },
  },
  {
    id: "40",
    src: "assets/artwork-40.jpg",
    aspect: 1.333,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on toned paper" },
    size: { zh: "", en: "" },
    zh: { title: "台中", sub: "" },
    en: { title: "Taichung", sub: "" },
  },
  {
    id: "31",
    src: "assets/artwork-31.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "芹壁聚落", sub: "" },
    en: { title: "Qinbi Village", sub: "" },
  },
  {
    id: "32",
    src: "assets/artwork-32.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "南竿遊客中心", sub: "" },
    en: { title: "Nangan Visitor Center", sub: "" },
  },
  {
    id: "33",
    src: "assets/artwork-33.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "仁愛沙灘", sub: "" },
    en: { title: "Ren'ai Beach", sub: "" },
  },
  {
    id: "34",
    src: "assets/artwork-34.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "芦ノ湖(右)", sub: "" },
    en: { title: "Lake Ashi (Right)", sub: "" },
  },
  {
    id: "35",
    src: "assets/artwork-35.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "芦ノ湖(左)", sub: "" },
    en: { title: "Lake Ashi (Left)", sub: "" },
  },
  {
    id: "36",
    src: "assets/artwork-36.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "上野恩賜公園", sub: "" },
    en: { title: "Ueno Park", sub: "" },
  },
  {
    id: "37",
    src: "assets/artwork-37.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "戶山公園", sub: "" },
    en: { title: "Toyama Park", sub: "" },
  },
  {
    id: "38",
    src: "assets/artwork-38.jpg",
    aspect: 0.8,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "強羅", sub: "" },
    en: { title: "Gora", sub: "" },
  },
  {
    id: "39",
    src: "assets/artwork-39.jpg",
    aspect: 1.25,
    year: 2025,
    series: "plein-air",
    medium: { zh: "油性粉彩、紙", en: "Oil pastel on paper" },
    size: { zh: "", en: "" },
    zh: { title: "新竹寫生日", sub: "" },
    en: { title: "Sketching Day in Hsinchu", sub: "" },
  },
];
