// All UI strings + the artist statement, in zh-TW and en.
window.COPY = {
  zh: {
    lang_label: "繁中",
    artist: "吳享龍",
    artist_en: "Dragom",
    role: "繪畫工作者",
    nav: {
      home: "首頁",
      works: "作品",
      series: "系列",
      statement: "創作論述",
      journal: "手記",
      about: "關於",
      contact: "聯絡",
    },
    landing: {
      eyebrow: "個人作品集 ｜ 二〇二一 – 二〇二四",
      hero_title: "在理性的縫隙中，",
      hero_title_2: "摸索一場安靜的崩落。",
      hero_lede:
        "二十件手繪作品，記錄潛意識湧動之處——當社會的鷹架抵不住內裡的洪流，個體將以何種姿態落地。",
      enter: "進入畫廊",
      featured_label: "本期主作 ／ Featured",
      index_label: "作品索引 ／ Index",
      manifesto_eyebrow: "創作論述 ／ Manifesto",
      manifesto_cta: "閱讀全文",
      scroll_hint: "向下，慢慢看",
    },
    statement_title: "創作論述",
    statement_subtitle: "Statement",
    statement_body: [
      "現代文明奠基在知識理論的基礎下，提供了人們仰賴邏輯推理的慣性。但在層層壓抑下，自我是無從抵抗的洪流，在內心湧動。",
      "而當這份賴以為繫的安全感崩裂，個體將何去何從？",
      "作者投身於潛意識的荒原，創造夢境裡的警世寓言，試圖在理性的縫隙中，摸索社會框架對心靈的禁錮與影響。",
    ],
    gallery: {
      title: "作品",
      subtitle: "Works",
      total: "共二十件",
      layout_label: "陳列方式",
      layouts: {
        spotlight: "聚光燈",
        grid: "網格",
        masonry: "瀑布流",
        editorial: "編輯",
      },
      filter_all: "全部",
      filter_series: "系列",
      caption_label: "作品說明",
      medium_label: "媒材",
      size_label: "尺寸",
      year_label: "年份",
      series_label: "系列",
      prev: "上一件",
      next: "下一件",
      view: "查看",
      back_to_index: "返回索引",
    },
    series_page: {
      title: "系列",
      subtitle: "Series",
      lede: "三組作品，從寓言走向結構，最後通過裂縫。",
      pieces: "件作品",
    },
    journal: {
      title: "手記",
      subtitle: "Journal",
      lede: "工作室裡的碎片、媒材的整理、過程中的速寫、偶爾的活動照片。把這裡當作一條時間的邊線，作品成形之前與之後的事都安放在此。",
      foot_hint: "拖一張圖進任何一格 ／ 它會記住",
    },
    about: {
      title: "關於",
      subtitle: "About",
      bio_eyebrow: "簡介",
      bio: [
        "吳享龍，創作以手繪為主，習於在粉彩、油彩與紙的觸感之間，安放一些理性難以收納的事物。",
        "近期創作圍繞夢境、框架與個體的位置展開——試圖把睡眠中浮現的圖像，重新組成可以與人對視的物件。",
      ],
      facts_eyebrow: "事實",
      facts: [
        ["主要媒材", "粉彩、油彩、紙"],
        ["創作主題", "夢境、潛意識、社會結構"],
        ["居住地", "台灣"],
      ],
      cv_eyebrow: "近期",
      cv: [
        ["2024", "個人創作系列《邊境的天際線》完成"],
        ["2023", "《框架》系列發表於個人線上展示"],
        ["2022", "投入《縫隙》系列創作"],
        ["2021", "開始長期手繪日誌計畫"],
      ],
    },
    contact: {
      title: "聯絡",
      subtitle: "Contact",
      lede: "歡迎邀稿、合作、徵件、收藏與課程提案。一般於三個工作日內回覆。",
      email_label: "電子郵件",
      ig_label: "Instagram",
      copy: "複製",
      copied: "已複製",
      open: "開啟",
      footer_note: "本網站作品著作權所有，未經同意請勿轉載。",
    },
    plaque: {
      catalog: "目錄編號",
      medium: "媒材",
      dimensions: "尺寸",
      year: "年份",
      series: "系列",
    },
  },
  en: {
    lang_label: "EN",
    artist: "Dragom",
    artist_en: "Wu Hsiang-Lung",
    role: "Painter",
    nav: {
      home: "Index",
      works: "Works",
      series: "Series",
      statement: "Statement",
      journal: "Journal",
      about: "About",
      contact: "Contact",
    },
    landing: {
      eyebrow: "Selected works ｜ 2021 – 2024",
      hero_title: "Feeling for a quiet collapse,",
      hero_title_2: "through the seams of reason.",
      hero_lede:
        "Twenty hand-drawn pieces from where the subconscious moves — when the social scaffolding fails to hold the current inside, how does the self land.",
      enter: "Enter the gallery",
      featured_label: "Featured work",
      index_label: "Index of works",
      manifesto_eyebrow: "Statement ／ Manifesto",
      manifesto_cta: "Read in full",
      scroll_hint: "Down. Take your time.",
    },
    statement_title: "Statement",
    statement_subtitle: "創作論述",
    statement_body: [
      "Modern civilization is built upon knowledge and theory — it grants us the habit of relying on logical reasoning. But beneath those compressing layers, the self is an irresistible current, surging from within.",
      "When the security we have built upon collapses, where does the individual go?",
      "The artist plunges into the wilderness of the subconscious, composing cautionary fables inside dreams — feeling, through the seams of reason, for how the social frame imprisons and reshapes the soul.",
    ],
    gallery: {
      title: "Works",
      subtitle: "作品",
      total: "Twenty pieces in total",
      layout_label: "Layout",
      layouts: {
        spotlight: "Spotlight",
        grid: "Grid",
        masonry: "Masonry",
        editorial: "Editorial",
      },
      filter_all: "All",
      filter_series: "Series",
      caption_label: "Caption",
      medium_label: "Medium",
      size_label: "Size",
      year_label: "Year",
      series_label: "Series",
      prev: "Previous",
      next: "Next",
      view: "View",
      back_to_index: "Back to index",
    },
    series_page: {
      title: "Series",
      subtitle: "系列",
      lede: "Three bodies of work — from fable, into structure, out through the seams.",
      pieces: "works",
    },
    journal: {
      title: "Journal",
      subtitle: "手記",
      lede: "Fragments from the studio, organising materials, in-process sketches, the occasional event photograph. Treat it as a line of time — anything that lives before and after a finished work goes here.",
      foot_hint: "drop an image into any slot ／ it will remember",
    },
    about: {
      title: "About",
      subtitle: "關於",
      bio_eyebrow: "Bio",
      bio: [
        "Dragom (Wu Hsiang-Lung) is a Taiwan-based painter working primarily by hand — placing, between the touch of soft pastel, oil and paper, things that reason has trouble filing away.",
        "Recent work circles around dreams, frames, and the position of the individual — taking images that surface in sleep and rebuilding them as objects you can hold a gaze with.",
      ],
      facts_eyebrow: "Facts",
      facts: [
        ["Primary media", "Soft pastel, oil, paper"],
        ["Subjects", "Dreams, the unconscious, social structure"],
        ["Based in", "Taiwan"],
      ],
      cv_eyebrow: "Selected",
      cv: [
        ["2024", "Series Skyline at the Border completed"],
        ["2023", "Series Frameworks released via personal channels"],
        ["2022", "Began the series Seams"],
        ["2021", "Started a long-form hand-drawn journal practice"],
      ],
    },
    contact: {
      title: "Contact",
      subtitle: "聯絡",
      lede: "Open to commissions, collaborations, open calls, acquisitions and teaching. Usually replies within three working days.",
      email_label: "Email",
      ig_label: "Instagram",
      copy: "Copy",
      copied: "Copied",
      open: "Open",
      footer_note: "All works © the artist. Please don't repost without permission.",
    },
    plaque: {
      catalog: "Catalog",
      medium: "Medium",
      dimensions: "Dimensions",
      year: "Year",
      series: "Series",
    },
  },
};

window.CONTACT = {
  email: "dragom.studio@protonmail.com",
  ig: "dragom.draws",
  ig_url: "https://instagram.com/dragom.draws",
};
